font_family      family="D2CodingLigature Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto


#background configuration
background_opacity 0.35
background_blur 1
background #212121
