font_family      family="D2CodingLigature Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto


#background configuration
background_opacity 0.65
background_blur 10
background #16191a
foreground #b3c6cc
