general {
    hide_cursor = true
    fail_timeout = 100
}

auth {
    pam:enabled = true
}

background { 
    monitor = 
    path = $HOME/.config/hypr/cards.jpg
    blur_passes = 2
    blur_size = 1
}

label {
    monitor = 
    text = $TIME12
    valign = none
    halign = center
    font_size = 22
    position = 0, 800 
}

input-field {
    monitor = 
    outer_color = rgba(255, 255, 255, 0)
    size = 500, 75
    fade_on_empty = false
    placeholder_text = Password
}

