general {
    lock_cmd = hyprlock || pidof hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' 
    inhibit_sleep = false
}

listener {
    timeout = 6000
    on-timeout = systemctl suspend
}

listener {
    timeout = 150
    on-timeout = brightnessctl -s set 5
    on-resume = brightnessctl -r
}

listener { 
    timeout = 150
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backligh
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
}
